### ISSUE TITLE
Render PDF pages to images

### ISSUE THREAD

**Issue by AmeerGN** [TomRoush/PdfBox-Android#3]
How can this library be used to render PDF pages to images similar to PDFImageWriter in Apache PDFBox

**Comment by tbook** [comment]
@Birdbrain2, Thanks for your work!  This is a great start to getting some better PDF support on Android.  I've looked at Joan Zapata's AndroidPDFView, but the GPL license is too restrictive.  If you do get the rendering to bitmaps working, that would be a big help for me, as well.

**Comment by widmoser** [comment]
In fact there seems a method to do that:

```java
PDFRenderer renderer = new PDFRenderer(document);
Bitmap b = renderer.renderImage(page);
```

Unfortunately this produces only an empty white image for me. I needed to load the file with the legacy loader though (see https://github.com/Birdbrain2/PdfBox-Android/issues/14).

**Comment by widmoser** [comment]
It seems that the operators are not fully implemented right?

**Comment by Birdbrain2** [comment]
No, some of them are missing. If you need one, it's best that you make a separate issue for that.

**Comment by varunmaini** [comment]
Hi birdbrain, the example you shared (https://github.com/apache/pdfbox/blob/trunk/tools/src/main/java/org/apache/pdfbox/tools/ExtractImages.java) uses java awt, which is not available on Android. Any suggestions as to how can we get the sample working on Android ? Thanks for the great library.

**Comment by Birdbrain2** [comment]
You should just basically need the extract method and ImageExtractorEngine.drawImage. The write2file method in drawImage can be replaced with something like this:

```
File file = new File(android.os.Environment.getExternalStorageDirectory().getAbsolutePath() + "/Download/" + name +".jpg");
FileOutputStream fOut = new FileOutputStream(file);
pdImage.getImage().compress(Bitmap.CompressFormat.JPEG, 100, fOut);
```

**Comment by massacreduck** [comment]
I'm working on a project requiring this function. 
It use kitkat, so there's no  the new class "PdfRenderer" included in lollipop. 
Is there a way for this library to render pdf on the view or  convert it into an image? 
If not, does anyone knows about any pdf-rendering library on android which is free for commercial-use?
What does the class "org.apache.pdfbox.rendering" do?
I got an empty image like widmoser did when I use the following code.
<code>
PDFRenderer renderer = new PDFRenderer(document);
Bitmap b = renderer.renderImage(page);
</code>

**Comment by Birdbrain2** [comment]
Currently. no. It's in development now, and basic text drawing should be available soon. The rendering package holds what has been done so far, but it still should just give you a blank/white image if you try to render the page. Unfortunately I don't know of any free rendering libraries for commercial use. Depending on what you're trying to do, you could try to have your app request to open the PDF so another PDF viewer installed on the device will open the file.

**Comment by sgonchar** [comment]
Hi, I also need render PDF to PNG files. When will you implement this functionality in pdfbox android library? 
Thank you

**Comment by Birdbrain2** [comment]
It's being worked on. Currently text is just about done, I just need to work out a few bugs.

**Comment by simply-jos** [comment]
Any progress on this?

**Comment by Birdbrain2** [comment]
Yes, but still not done. Depending on how complex the PDF is and what features it has, it may render correctly, but there are still features that will mess up or be ignored.

**Comment by amine-khadmaoui** [comment]
Any progress on this feature? 
I also need to render PDF (with images into it) to Bitmap. When do you think it will be done? 
Thanks and great job!

**Comment by Birdbrain2** [comment]
I haven't got much of a chance to work on it recently. Text, shapes, and JPG images should draw fine. PNG images are ignored and forms aren't draw right, which are the two of the bigger problems.

**Comment by antopeti** [comment]
Any progress on this?

**Comment by TomRoush** [comment]
As of today, PNGs should be working. Forms may still not draw right. If you notice any other elements that aren't drawing right, please let me know/

**Comment by imsnow** [comment]
Hi, Tom! Can i use pdfbox to display pdf file now?
I'm trying to use <code>Bitmap bitmap = render.renderImage(index);</code>, but app catchs the exception <code>java.io.IOException: Invalid color space kind: COSName{ICCBased}</code>

**Comment by TomRoush** [comment]
That sounds like part of the PDF you're trying to render is using a colorspace that hasn't been implemented yet. If you can post a bit more of the stacktrace in a new issue I can take a look at adding what you need.

**Comment by VivianaGarces** [comment]
Hi Tom. Thank you for working on this port, This has helped me a lot. 
I'm trying to convert a PDF to images but I'm getting a NullPointerException when I try to use the renderImage method. I thought it was a problem with my file and logged the PDDocument number of pages with the file size but they're not empty or null. I'ts only one page...This is what I'm getting
```java
 Caused by: java.lang.NullPointerException
            at android.graphics.Paint.setStrokeJoin(Paint.java:947)
            at org.apache.pdfbox.rendering.PageDrawer.setStroke(PageDrawer.java:505)
            at org.apache.pdfbox.rendering.PageDrawer.strokePath(PageDrawer.java:519)
            at org.apache.pdfbox.contentstream.operator.graphics.StrokePath.process(StrokePath.java:20)
            at org.apache.pdfbox.contentstream.PDFStreamEngine.processOperator(PDFStreamEngine.java:802)
            at org.apache.pdfbox.contentstream.PDFStreamEngine.processStreamOperators(PDFStreamEngine.java:464)
            at org.apache.pdfbox.contentstream.PDFStreamEngine.processStream(PDFStreamEngine.java:438)
            at org.apache.pdfbox.contentstream.PDFStreamEngine.processPage(PDFStreamEngine.java:147)
            at org.apache.pdfbox.rendering.PageDrawer.drawPage(PageDrawer.java:118)
            at org.apache.pdfbox.rendering.PDFRenderer.renderPage(PDFRenderer.java:124)
            at org.apache.pdfbox.rendering.PDFRenderer.renderImage(PDFRenderer.java:87)
            at org.apache.pdfbox.rendering.PDFRenderer.renderImage(PDFRenderer.java:43)
            at com.printer.appPrint.MainPrintActivity$GetPdfImages.extImages(MainPrintActivity.java:47)
```

Line 47 is `bitmap = renderer.renderImage(0);`. Thanks for your help

**Comment by TomRoush** [comment]
VivianaGarces,
That bug has been fixed. If you build the library from the Github source, you shouldn't get that error anymore.

**Comment by VivianaGarces** [comment]
I've cloned the repository and run gradle.bat to build it. Then added the .jar file called pdfbox-android-1.8.9.1-sources.jar in my project (I use Android Studio) but the libraries aren't reachable. Am I doing something wrong?

My build.gradle file looks like this:

    apply plugin: 'com.android.application'

    android {
    compileSdkVersion 21
    buildToolsVersion "22.0.1"
    packagingOptions {
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/NOTICE.txt'
    }
    defaultConfig {
        applicationId "com.viviana.myapp"
        minSdkVersion 15
        targetSdkVersion 21
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    }
    repositories {
       jcenter()
    }
    dependencies {
        compile fileTree(include: ['*.jar'], dir: 'libs')
        compile 'com.android.support:appcompat-v7:22.2.0'
        compile project(':itextg-5.5.5')
        compile project(':pdfbox-android-1.8.9.1-sources')
        compile project(':pg-1.52.0.0')
        compile project(':httpmime-4.3.1')
        compile project(':httpcore-4.4')
        compile project(':core-1.52.0.0')
        compile project(':pkix-1.52.0.0')
        compile project(':prov-1.52.0.0')
        compile project(':commons-io-2.4')
    }

**Comment by TomRoush** [comment]
VivianaGarces,
You'll need to generate an aar to have the necessary resources. If you run ```gradle :library:build``` an aar will be generated in build/outputs. You should then be able to import the module into Android Studio.

**Comment by MathiasKrill** [comment]
Hi is there a progress in creating the images ? 
The methode Bitmap bitmap = pdfRenderer.renderImage(0, 1f, Bitmap.Config.ARGB_8888); works well so far - but the image is bad zoomable (no high resolution). Is there a way to create serveral images - one with a high resolution for example ?

Best wishes Mathias

**Comment by TomRoush** [comment]
The second parameter of renderImage is a scale factor. You can use higher numbers to increase the resolution.

**Comment by isolpak1** [comment]
Any update on this?

And how to save the image?
http://stackoverflow.com/questions/23326562/apache-pdfbox-convert-pdf-to-images
````
PDDocument document = PDDocument.load(new File(pdfFilename));
PDFRenderer pdfRenderer = new PDFRenderer(document);
for (int page = 0; page < document.getNumberOfPages(); ++page)
{ 
    BufferedImage bim = pdfRenderer.renderImageWithDPI(page, 300, ImageType.RGB);

    // suffix in filename will be used as the file format
    ImageIOUtil.writeImage(bim, pdfFilename + "-" + (page+1) + ".png", 300);
}
document.close();
````
As **BufferedImage**  and **ImageIOUtil** are not available on Android

**Comment by isolpak1** [comment]
````java
Bitmap savePdfThumb(File file) {
    try {
            PDDocument pdf = PDDocument.load(file);
            PDFRenderer pdfRenderer = new PDFRenderer(pdf);
            Bitmap bmp = pdfRenderer.renderImage(0, 0.5f, Bitmap.Config.ARGB_8888);
            return bmp;
        } catch(Exception e) {
            Log.e("--", "savePdfThumb  : " + e.toString());
        }
        return null;
    }
````

is producing following **exception**
````
savePdfThumb  : java.lang.NullPointerException: Attempt to read from field 'int android.graphics.Paint$Cap.nativeInt' on a null object reference

**Comment by TomRoush** [comment]
I think that this was an old bug in the rendering code. If you build the latest version from source, this problem should be resolved.

**Comment by isolpak1** [comment]
I am using **org.apache:pdfbox-android:1.8.9.0** and still unable to generate image from pdf page no. 1 (just like WhatsApp)

Any help would be highly appreciated...

**Comment by TomRoush** [comment]
You'll need to build the library yourself. You can look at the sample app's Gradle setup for one way to do it, or run `gradle build` and build an AAR library file. The generated file can be found `library\build\outputs\aar` and easily added to your Android Studio project with New->New module.

**Comment by isolpak1pc** [comment]
Done using following library
http://stackoverflow.com/questions/38828396/generate-thumbnail-of-pdf-in-android

**Comment by TomRoush** [comment]
Closing this issue as rendering works for most PDFs. Further rendering problems should go in their own issue.
